images/urls.py
from django.urls import path

from . import views


app_name = 'images'

urlpatterns = [
	path('', views.home, name='home'),
	path('image/upload', views.upload_image, name='image_upload'),
	path('image/<int:image_id>', views.view_image, name='image'),
	path('image/search/', views.search_image, name='image_search'),
	path('popular', views.popular_images, name='images_popular'),
	path('latest', views.latest_images, name='image_latest'),
	path('my_uploads', views.my_uploads, name='my_uploads'),
	path('image/delete/<int:image_id>', views.delete_image, name='image_delete'),
	path('image/edit/<int:image_id>', views.edit_image, name='image_edit')
]

img_host/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings

urlpatterns = [
	path('admin/', admin.site.urls),
	path('users/', include('users.urls')),
	path('', include('images.urls')),
	path('', include('voting.urls')),
]

if settings.DEBUG:
	from django.conf.urls.static import static

	urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'users'

urlpatterns = [
	path('register/', views.user_register, name='register'),
	path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
	path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

images/models.py
from django.db import models
from django.conf import settings


class Image(models.Model):
	title = models.CharField(max_length=40)
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	img_file = models.ImageField()
	uploaded = models.DateTimeField(auto_now_add=True)

	score = models.IntegerField(default=0)

	def __str__(self):
		return self.title

images/forms.py
from django.forms import ModelForm

from .models import Image


class ImageForm(ModelForm):
	class Meta:
		model = Image
		fields = ['title', 'img_file']

images/views.py
from datetime import datetime, timedelta

from django.shortcuts import get_object_or_404, redirect, render

from .models import Image
from .forms import ImageForm
from voting.models import Vote


def home(request):
	images = Image.objects.all().order_by("-uploaded")[:10]

	score_dict = {}
	votes_dict = {}

	for image in images:
		score_dict[image.id] = image.score

	if request.user.is_authenticated:
		votes = Vote.objects.filter(image__in=images, user=request.user)
		for vote in votes:
			votes_dict[vote.image.id] = vote

	context = {'images': images, 'votes_dict': votes_dict, 'score_dict': score_dict}

	return render(request, 'images/image_list.html', context)


def view_image(request, image_id):
	image = Image.objects.get(id=image_id)

	if request.user.is_authenticated:
		try:
			user_vote = Vote.objects.get(user=request.user, image=image)  # only the vote from the current user
		except Vote.DoesNotExist:
			user_vote = None
	else:
		user_vote = None

	context = {'image': image, 'user_vote': user_vote}

	return render(request, 'images/image.html', context)


def popular_images(request):
	images = Image.objects.all().order_by("-score")

	score_dict = {}
	votes_dict = {}

	for image in images:
		score_dict[image.id] = image.score

	if request.user.is_authenticated:
		votes = Vote.objects.filter(image__in=images, user=request.user)
		for vote in votes:
			votes_dict[vote.image.id] = vote

	context = {'images': images, 'votes_dict': votes_dict, 'score_dict': score_dict}

	return render(request, 'images/image_list.html', context)


def latest_images(request):
	period = request.GET.get('p', 'week')

	if period == 'day':
		period = datetime.now() - timedelta(days=1)
	if period == 'week':
		period = datetime.now() - timedelta(days=7)
	if period == 'month':
		period = datetime.now() - timedelta(days=30)

	images = Image.objects.all().order_by("-uploaded").filter(uploaded__gt=period)

	score_dict = {}
	votes_dict = {}

	for image in images:
		score_dict[image.id] = image.score

	if request.user.is_authenticated:
		votes = Vote.objects.filter(image__in=images, user=request.user)
		for vote in votes:
			votes_dict[vote.image.id] = vote

	context = {'images': images, 'votes_dict': votes_dict, 'score_dict': score_dict}

	return render(request, 'images/image_list.html', context)


def upload_image(request):
	if request.method == 'POST':
		image_form = ImageForm(request.POST, request.FILES)
		if image_form.is_valid():
			image = image_form.save(commit=False)
			image.user = request.user
			image.save()
			return redirect('images:image', image_id=image.id)
	else:
		image_form = ImageForm()
	context = {'image_form': image_form}
	return render(request, "images/upload_image.html", context)


def my_uploads(request):
	images = Image.objects.all().filter(user=request.user)
	context = {'images': images}
	return render(request, "images/my_uploads.html", context)


def delete_image(request, image_id):
	image = get_object_or_404(Image, id=image_id)

	image.delete()
	return redirect('images:my_uploads')


def edit_image(request, image_id):
	image = get_object_or_404(Image, id=image_id)

	if request.method == 'POST':
		image_form = ImageForm(request.POST, request.FILES, instance=image)
		if image_form.is_valid():
			image_form.save()
			return redirect('images:image', image_id=image.id)
	else:
		image_form = ImageForm(instance=image)
	context = {'image': image, 'image_form': image_form}
	return render(request, "images/image_edit.html", context)


def search_image(request):
	query = request.GET.get('s', None)

	if query is None:
		images = None
	else:
		images = Image.objects.all().filter(title__startswith=query)

	score_dict = {}
	votes_dict = {}

	for image in images:
		score_dict[image.id] = image.score

	if request.user.is_authenticated:
		votes = Vote.objects.filter(image__in=images, user=request.user)
		for vote in votes:
			votes_dict[vote.image.id] = vote

	context = {'images': images, 'votes_dict': votes_dict, 'score_dict': score_dict}

	return render(request, 'images/image_list.html', context)

images/templates/images/image.html
{% extends "base.html" %}


{% block content %}
	{% include 'images/img_post.html' %}
{% endblock %}

images/templates/images/image_edit.html
{% extends "base.html" %}


{% block content %}
	<div class="row my-5">
		<div class="col my-2">
			<h2>Upload a file!</h2>
			<form action="{% url 'images:image_edit' image.id%}" method="post" enctype="multipart/form-data" class="my-2 col" id="form_file">
				{% csrf_token %}
				{{ image_form.as_p }}
				<button type="submit" class="btn btn-primary">Submit</button>
			</form>
		</div>
	</div>
{% endblock %}

{#  {{ image_form.title.errors }}			{{ image_form.title.label_tag }}			{{ image_form.title }} #}

images/templates/images/image_list.html
{% extends "base.html" %}
{% load get_item %}

{% block content %}
	{% if images %}
		<h1>Today's Images!</h1>
		{% for image in images %}
			{% with user_vote=votes_dict|get_item:image.id score=score_dict|get_item:image.id %}
				{% include 'images/img_post.html' %}
			{% endwith %}
		{% endfor %}
	{% else %}
		<p>No images uploaded yet :(</p>
	{% endif %}
{% endblock %}

images/templates/images/img_post.html
<div class="row my-5">
	<div class="col">
		<div class="card">
			<div class="card-header">
				<a href="{% url 'images:image' image.id %}"><h6>{{ image.title }} by {{ image.user }}</h6></a>
			</div>
			<div class="card-body">
				<img class="img-fluid card-img" src="{{ image.img_file.url }}" alt="{{ image.img_file.name }}">
			</div>
			<div class="card-footer">
				{% if  user.is_authenticated %}
					{% if user_vote is None or user_vote.vote is None %}
						<a class="card-link" href="javascript:like({{ image.id }})" id="like_{{ image.id }}"><span><i class="fas fa-arrow-up" aria-hidden="true"></i></span></a>
						<a class="card-link" href="javascript:dislike({{ image.id }})" id="dislike_{{ image.id }}"><span><i class="fas fa-arrow-down" aria-hidden="true"></i></span></a>
					{% else %}
						{% if user_vote.vote is True %}
							<a class="card-link text-success" href="javascript:like({{ image.id }})" id="like_{{ image.id }}"><span><i class="fas fa-arrow-up" aria-hidden="true"></i></span></a>
							<a class="card-link" href="javascript:dislike({{ image.id }})" id="dislike_{{ image.id }}"><span><i class="fas fa-arrow-down" aria-hidden="true"></i></span></a>
						{% elif user_vote.vote is False %}
							<a class="card-link" href="javascript:like({{ image.id }})" id="like_{{ image.id }}"><span><i class="fas fa-arrow-up" aria-hidden="true"></i></span></a>
							<a class="card-link text-danger" href="javascript:dislike({{ image.id }})" id="dislike_{{ image.id }}"><span><i class="fas fa-arrow-down" aria-hidden="true"></i></span></a>
						{% endif %}
					{% endif %}
				{% else %}
					<a class="card-link" data-toggle="tooltip" data-placement="bottom" title="You need to login" href="javascript:void(0)"><span><i class="fas fa-arrow-up" aria-hidden="true"></i></span></a>
					<a class="card-link" data-toggle="tooltip" data-placement="bottom" title="You need to login" href="javascript:void(0)"><span><i class="fas fa-arrow-down" aria-hidden="true"></i></span></a>
				{% endif %}

				<span id="score_{{ image.id }}"> {{ image.score }}</span>
				<span> on {{ image.uploaded }}</span>
			</div>
		</div>
	</div>
</div>

images/templates/images/my_uploads.html
{% extends "base.html" %}

{% block content %}

	<h2> My uploads!</h2>


	<table class="table">
		<thead>
		<tr>
			<th scope="col">Name</th>
			<th scope="col">Score</th>
			<th scope="col">Date</th>
			<th scope="col">Actions</th>
		</tr>
		</thead>
		<tbody>

		{% for image in images %}
			<tr>
				<td><a href="{% url 'images:image' image.id %}">{{ image.title }}</a></td>
				<td>{{ image.score }}</td>
				<td>{{ image.uploaded }}</td>
				<td>
					<a href="{% url 'images:image_edit' image.id %}"><span><i class="fas fa-edit" aria-hidden="true"></i></span></a>
					<a href="{% url 'images:image_delete' image.id %}"><span><i class="fas fa-trash-alt" aria-hidden="true"></i></span></a>
				</td>
			</tr>
		{% endfor %}
		</tbody>
	</table>
{% endblock %}

images/templates/images/upload_image.html
{% extends "base.html" %}


{% block content %}
	<div class="row my-5">
		<div class="col my-2">
			<h2>Upload a file!</h2>
			<form action="{% url 'images:image_upload' %}" method="post" enctype="multipart/form-data" class="my-2 col" id="form_file">
				{% csrf_token %}
				{{ image_form.as_p }}
				<button type="submit" class="btn btn-primary">Submit</button>
			</form>
		</div>
	</div>
{% endblock %}