images/urls.py
from django.urls import path

from . import views


app_name = 'images'

urlpatterns = [
	path('', views.home, name='home'),
	path('image/upload', views.upload_image, name='image_upload'),
	path('image/<int:image_id>', views.view_image, name='image'),
	path('image/search/', views.search_image, name='image_search'),
	path('popular', views.popular_images, name='images_popular'),
	path('latest', views.latest_images, name='image_latest'),
	path('my_uploads', views.my_uploads, name='my_uploads'),
	path('image/delete/<int:image_id>', views.delete_image, name='image_delete'),
	path('image/edit/<int:image_id>', views.edit_image, name='image_edit')
]

img_host/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings

urlpatterns = [
	path('admin/', admin.site.urls),
	path('users/', include('users.urls')),
	path('', include('images.urls')),
	path('', include('voting.urls')),
]

if settings.DEBUG:
	from django.conf.urls.static import static

	urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'users'

urlpatterns = [
	path('register/', views.user_register, name='register'),
	path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
	path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Img Host</title>

	<!-- Bootstrap css -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
	      integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	{% block css %}
	{% endblock css %}


</head>
<body style="padding-top: 65px;">
<header>
	<nav class="navbar fixed-top navbar-expand navbar-dark bg-primary">
		<a class="navbar-brand" href="/">Img Host</a>
		<div class="navbar-nav mr-auto">
			<div class="nav-item dropdown">
				<a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Latest Uploads</a>
				<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
					<a class="dropdown-item" href="{% url 'images:image_latest' %}?p=day">This Days's</a>
					<a class="dropdown-item" href="{% url 'images:image_latest' %}?p=week">This Week's</a>
					<a class="dropdown-item" href="{% url 'images:image_latest' %}?p=month">This Month's</a>
				</div>
			</div>
			<a class="nav-item nav-link text-light" href="{% url 'images:images_popular' %}">Most Popular</a>
			<form class="form-inline" method="get" action="{% url 'images:image_search' %}">
				<div class="form-group">
					<input type="text" class="form-control" placeholder="Search" name="s">
				</div>
				<button type="submit" class="btn btn-primary">Submit</button>
			</form>
		</div>
		<div class="navbar-nav ml-auto">
			{% if request.user.is_authenticated %}
				<div class="nav-item dropdown">
					<a class="nav-link dropdown-toggle text-light text-capitalize" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ user }}</a>
					<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
						<a class="dropdown-item" href="{% url 'images:image_upload' %}">Upload Image</a>
						<a class="dropdown-item" href="{% url 'images:my_uploads' %}">My Uploads</a>
						<a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
					</div>
				</div>
			{% else %}
				<a class="nav-item nav-link text-light" href="{% url 'users:login' %}">Login</a>
				<a class="nav-item nav-link text-light" href="{% url 'users:register' %}">Register</a>
			{% endif %}
		</div>
	</nav>
</header>
<main role="main">
	<div class="container">
		{% block content %}
		{% endblock %}
	</div>
</main>
<!-- JS -->
<script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script defer src="https://use.fontawesome.com/releases/v5.6.1/js/all.js" integrity="sha384-R5JkiUweZpJjELPWqttAYmYM1P3SNEJRM6ecTQF05pFFtxmCO+Y1CiUhvuDzgSVZ" crossorigin="anonymous"></script>
<script type="text/javascript" src="{% static 'js/custom.js' %}"></script>
{% block js %}
{% endblock js %}
</body>
</html>